UX PARITY IMPLEMENTATION: Moonlanding vs Friday-staging + MyWorkReview-staging
================================================================================
Status: AUDIT COMPLETE - Implementation not yet started
Audit Date: 2026-02-08

This .prd contains only MISSING and PARTIAL items requiring implementation.
PRESENT items (139) have been verified and removed.

MISSING: 73 items (not implemented)
PARTIAL: 68 items (exists but incomplete)
TOTAL REMAINING: 141 items

================================================================================
CRITICAL MISSING (must implement for 1:1 parity)
================================================================================

- [ ] F-AUTH-03: Password reset page + API endpoint (Friday src/ForgotPassword.js)
- [ ] F-FEE-01: Engagement fee split - field, UI tab, sliders, validation (Friday EngagementsEdit.js)
- [ ] F-TEAM-03: Team avatar group display component (Friday auditingTeamAvatars.js)
- [ ] F-NOTIF-02: Notification trigger dialog (Friday SettingsEngagementNotificationTriggerDialog.js)
- [ ] F-CLIENT-07: Client user management dialog (Friday ClientManageUserDialog.js)
- [ ] F-CLIENT-08: Client user replace dialog across engagements (Friday ClientUserReplaceDialog.js)
- [ ] F-CLIENT-09: Client test email dialog (Friday ClientTestEmailDialog.js)
- [ ] F-CLIENT-10: Client risk assessment dialog (Friday ClientRiskAssessmentDialog.js)
- [ ] F-RFI-08: RFI section drag-and-drop reorder (Friday EngagementSectionOrderDialog.js)
- [ ] F-RFI-10: RFI question edit dialog (Friday EditRFIQuestionDialog.js)
- [ ] F-RFI-16: RFI question client user assignment dialog (Friday AttachRFIQuestionClientUserDialog.js)
- [ ] F-RFI-17: RFI bulk client user assignment (Friday AttachRFIClientUserDialog.js)
- [ ] F-RFI-18: RFI bulk deadline setting (Friday AttachBulkDeadlinesRFIDialog.js)
- [ ] F-RFI-20: RFI response attachment preview (Friday ResponseAttachmentPreview.js)
- [ ] F-RFI-21: RFI response attachment lazy load (Friday ResponseAttachmentLoad.js)
- [ ] F-RFI-22: RFI report generation (Friday GetRFIReport.js + RFIReport.js)
- [ ] F-RFI-23: RFI email reminders dialog per question (Friday RFIItemReminderDialog.js)
- [ ] F-RFI-28: RFI template select field dropdown (Friday RFITemplateSelectField.js)
- [ ] F-RFI-30: DataGrid grouping for RFI (section/assigned/status/flagged/ML queries)
- [ ] F-RFI-31: Hide completed questions toggle
- [ ] F-RFI-32: Unread message count badges per RFI question
- [ ] F-RFI-33: RFI item dialog (Friday RFIEngagementItemDialog.js)
- [ ] F-RFI-34: RFI attach dialog (Friday AttachRFIDialog.js)
- [ ] F-RFI-35: RFI attach question dialog (Friday AttachRFIQuestionDialog.js)
- [ ] F-RFI-36: RFI response choice box (Friday ResponseChoiceBox.js)
- [ ] F-RFI-37: Color picker for RFI sections (Friday ColorPickerDialog.js)
- [ ] F-IMPORT-01: Import review queries from MWR (Friday ImportReviewQueriesDialog.js)
- [ ] F-SEARCH-01: Engagement file search dialog (Friday RFIEngagementFileSearchDialog.js)
- [ ] F-POSTRFI-02: Post-RFI journal dialog (Friday RFIEngagementPostRFIJournalDialog.js)
- [ ] F-POSTRFI-03: Post-RFI file upload (Friday uploadPostRFIFiles.js)
- [ ] F-PUSH-01: Push to MWR dialog (Friday PushMWRDialog.js)
- [ ] F-FILE-03: Zip file creation for multiple file download
- [ ] F-FILE-04: Cross-engagement file picker (Friday ChooseFilesFromOtherEngagementsDialog.js)
- [ ] F-FILE-06: User CV upload (Friday uploadUserCV.js)
- [ ] F-FILE-07: Quick view attachment inline preview (Friday QuickViewAttachment.jsx)
- [ ] F-FILE-08: RFI response attachment preview (Friday RFIResponseAttachmentPreview.js)
- [ ] F-BUILD-01: Build/deployment logs page (Friday BuildLogsPage.js)
- [ ] F-EMAIL-03: Email receive dialog UI (Friday EmailReceiveDialog.js)
- [ ] F-DG-01: DataGrid Premium row grouping capability
- [ ] F-DG-04: DataGrid Premium detail panels with expandable rows
- [ ] F-DG-05: DataGrid Premium reference/examples
- [ ] F-UI-05: Drag-and-drop reordering library + implementation
- [ ] F-UI-06: Date choice dialogs (Friday EngagementDateChoiceDialog.js)
- [ ] F-UI-07: AI Tool component (Friday AiTool.js)
- [ ] F-UI-09: Linear progress label component
- [ ] F-UI-10: Circular progress label component
- [ ] F-UI-11: Engagement progress label component
- [ ] F-UI-17: Engagement card item view (Friday EngagementCardItem.js)
- [ ] F-PDF-09: PDF Tip/TipContainer for highlight creation tooltip
- [ ] F-PDF-12: PDF bounding rect calculation lib
- [ ] F-PDF-13: PDF area-as-PNG capture lib
- [ ] F-PDF-14: PDF optimize-client-rects lib
- [ ] F-PDF-15: PDF pdfjs-dom helpers lib
- [ ] F-PDF-16: PDF get-client-rects lib
- [ ] F-PDF-19: PDF ConvertDataUrlFile component
- [ ] F-PDF-21: PDF MobileResizableRectangle for touch devices
- [ ] F-MISC-01: Global tags system
- [ ] F-MISC-10: Engagement checklist push to MWR dialog
- [ ] M-REV-05: Review template choice dialog (MWR FileReviewTemplateChoice.tsx)
- [ ] M-REV-06: Review context menu (MWR FileReviewMenu.tsx)
- [ ] M-PDF-07: Response attachment preview (MWR ResponseAttachmentPreview.tsx)
- [ ] M-PDF-08: Response attachment load (MWR ResponseAttachmentLoad.tsx)
- [ ] M-PDF-16: Area highlight image load (MWR AreaHighlightImageLoad.tsx)
- [ ] M-PDF-17: Retry highlight dialog (MWR RetryHighlightDialog.tsx)
- [ ] M-PDF-18: Mobile resizable rectangle (MWR MobileResizableRectangle.tsx)
- [ ] M-FLAG-01: Review flags management dialog (MWR FileReviewFlagDialog.tsx)
- [ ] M-TAG-01: Review tags management dialog (MWR FileReviewTagsDialog.tsx)
- [ ] M-VALUE-01: Review WIP value dialog (MWR FileReviewValueDialog.tsx)
- [ ] M-DATE-01: Review deadline date dialog (MWR FileReviewDateDialog.tsx)
- [ ] M-GROUP-01: Review list grouping (template/flag/stage/creator/manager/team)
- [ ] M-HIDE-01: Hide empty reviews toggle
- [ ] M-NOTIF-01: Review notification dialog manual send (MWR FileReviewNotificationDialog.tsx)
- [ ] M-SECT-02: Section reports (MWR SectionReport.tsx + GetSectionReport.tsx)
- [ ] M-MOB-01: Mobile review cards (MWR MobileReviewCard.tsx)
- [ ] M-MOB-02: Mobile engagement cards (MWR MobileEngagementCard.tsx)
- [ ] M-HOME-01: Home tabs tabbed view (MWR HomeTabs.tsx)
- [ ] M-CHECK-06: Push checklist cross-reference (unified system equivalent)
- [ ] M-AI-01: FlexUp AI chat interface (MWR FlexUpView.tsx + FlexUpChat.tsx)
- [ ] M-AI-02: FlexUp Friday cross-app AI chat (MWR FlexUpFridayChat.tsx)
- [ ] M-AI-03: FlexUp report generation (MWR FlexUpReport.tsx + GetFlexUpReport.tsx)
- [ ] M-AI-04: FlexUp attachment preview (MWR FlexAttachmentPreview.tsx)
- [ ] M-AI-07: Push queries to Friday dialog (MWR PushQueriesToMyFridayDialog.tsx)
- [ ] M-FILE-02: Upload Friday files cross-app (MWR uploadFridayFilesToApi.tsx)
- [ ] M-FILE-05: File attachment bar (MWR FileReviewAttachmentBar.tsx)
- [ ] M-FILE-06: File links bar (MWR FileReviewLinksBar.tsx)
- [ ] M-FILE-07: Quick view attachment (MWR QuickViewAttachment.tsx)
- [ ] M-FILE-08: Review attachment choice dialog (MWR ReviewAttachmentChoiceDialog.tsx)
- [ ] M-SET-08: Review settings page (MWR SettingsFileReviewSettings.tsx)
- [ ] M-SET-09: File review settings page (MWR SettingsFileReviewSettings.tsx)
- [ ] M-UI-02: Tooltip info bubbles (MWR FileReviewInfoBubble.tsx + FileReviewToolTip.tsx)
- [ ] M-UI-06: Linear progress labels (3 variants)
- [ ] M-UI-07: Circular progress label
- [ ] M-UI-12: Response choice box (MWR ResponseChoiceBox.tsx)
- [ ] M-UI-13: Response attachment component (MWR ResponseAttachment.tsx)
- [ ] M-UI-16: AI Tool component (MWR AiTool.tsx)
- [ ] M-UI-17: Sidebar review details panel (MWR SidebarReviewDetails.tsx)
- [ ] M-HOOK-02: useGetUserAvatar hook
- [ ] M-HOOK-03: useThrottledMediaQuery hook
- [ ] M-MISC-01: Global tags system
- [ ] M-MISC-04: File review calculations (MWR FileReviewCalcs.tsx)
- [ ] M-MISC-05: Friday globals cross-app references (MWR fridayGlobals.tsx)
- [ ] M-MISC-06: Friday team dialog (MWR FridayTeamDialog.tsx)
- [ ] M-MISC-07: Friday due date dialog (MWR FridayDueDateDialog.tsx)
- [ ] M-MISC-11: Convert data URL to file utility

================================================================================
PARTIAL (exists but needs completion for parity)
================================================================================

- [ ] F-AUTH-06: Auto-logout idle detection - add idle timer, warning dialog, session refresh on interaction
- [ ] F-AUTH-07: AuthContext equivalent - client-side global state for allUsers, teams, templates, entityTypes
- [ ] F-NAV-01: Sidebar menu - verify items match Friday menu structure/order/grouping
- [ ] F-NAV-02: Route definitions - add /password-reset route, /unauthorized page, team-scoped routes
- [ ] F-NAV-03: Layout - add AuditorLayout filtering for auditor user type
- [ ] F-NAV-04: Mobile navigation - custom responsive breakpoint hook
- [ ] M-NAV-01: MWR sidebar - add MWR-specific menu items (Start Review, Active, Priority, History, Archive)
- [ ] M-NAV-02: MWR route definitions - verify URL structure matches MWR patterns
- [ ] F-ENG-05: Engagement list - add grouping, detail panels, expandable rows, fee split columns
- [ ] F-ENG-08: Engagement search - dedicated SearchField component with real-time filtering
- [ ] F-ENG-09: Client engagement view - dedicated client-facing layout with different fields
- [ ] F-LIFE-02: Stage transition dialog - add stage visualization, confirmation, reason input
- [ ] F-LIFE-04: Stage selection UI - visual stage pipeline/progress component
- [ ] F-DET-05: Activity history - dedicated dialog/panel UI component
- [ ] F-TEAM-01: Team assignment dialog - dedicated team user picker with multi-select, avatars, search
- [ ] F-TEAM-02: Team selector - rich multi-user selector with avatars and search
- [ ] F-REC-02: Recreation logs - dedicated settings page/UI
- [ ] F-LETTER-01: Engagement letter dialog - frontend UI for generate/upload/status/template selection
- [ ] F-LETTER-02: Engagement letter template upload - dedicated UI
- [ ] F-NOTIF-01: Engagement notification settings - settings UI for enabling/disabling notifications
- [ ] F-CLIENT-06: Client home/dashboard - dedicated page with summary stats
- [ ] F-CLIENT-11: Client info utility - verify server-side equivalent covers all client info needs
- [ ] F-CLIENT-12: Client entity details - verify spec definitions cover all needed fields
- [ ] F-RFI-07: RFI section CRUD - dedicated management UI with color coding
- [ ] F-RFI-29: RFI template list function - verify server-side template loading covers all needs
- [ ] F-CHAT-02: Team chat - add UI toggle for team-only channel, visual separation of messages
- [ ] F-FILE-05: Upload engagement details file - verify file storage service parity
- [ ] F-SET-01: Settings home - dedicated landing page with section navigation
- [ ] F-SET-02: Settings view/layout - dedicated settings layout wrapper
- [ ] F-SET-07: Settings RFI sections - dedicated page with color picker and ordering
- [ ] F-SET-11: Settings engagement notifications - settings UI for notification configuration
- [ ] F-SET-12: Settings integrations - settings UI for managing integration credentials/API keys
- [ ] F-SET-13: Settings recreation logs - dedicated settings page
- [ ] F-DG-02: DataGrid sorting - upgrade to multi-column sort
- [ ] F-DG-03: DataGrid filtering - upgrade to column-level filters
- [ ] F-UI-04: Empty state containers - dedicated component with illustration/icon
- [ ] F-UI-08: Status label - verify visual style covers all Friday status types
- [ ] F-UI-12: Separator line - verify Mantine Divider covers all use cases
- [ ] F-UI-15: Expand more - verify Mantine Accordion covers all use cases
- [ ] F-UI-16: User avatar - dedicated component with status indicator
- [ ] F-SW-02: Service worker update banner - add version change notification UI
- [ ] F-GUARD-02: NonClerkRoute - verify permission checks block clerks from same routes
- [ ] F-GUARD-03: TeamAuthRoute - verify entity-level access covers team-scoped routes
- [ ] F-GUARD-04: ManagerPartnerLayout - verify spec-level permissions block clerks from settings
- [ ] F-GUARD-05: PartnerLayout - verify permission service blocks non-partners
- [ ] F-GUARD-06: UnauthorizedRoute - verify error-403.jsx covers all unauthorized scenarios
- [ ] F-GUARD-07: ProtectedLayout - verify app-shell.jsx covers all authenticated layout needs
- [ ] F-HOOK-01: useGetToken - verify server-side session covers all token needs
- [ ] F-HOOK-03: useGetUserType - verify server-side user.role covers all type checks
- [ ] F-HOOK-04: useResponsiveScreen - custom responsive hook or verify Mantine breakpoints suffice
- [ ] F-HOOK-05: useUserBelongsToTeam - verify server-side permission checks cover team membership
- [ ] F-HOOK-06: useLogQuestionActivity - verify server-side activity logging covers all needs
- [ ] F-MISC-02: Conversions utility - verify utils.js + date-utils.js cover all conversions
- [ ] F-MISC-03: Firebase functions - verify all Firebase API calls have Moonlanding equivalents
- [ ] F-MISC-05: Splash screen - branded splash screen
- [ ] F-MISC-07: Loader context - verify per-component loading covers global loading needs
- [ ] F-MISC-08: Highlight context - verify per-component state covers global highlight needs
- [ ] F-PDF-01: PDF Editor dialog - full editor dialog wrapper with open/close from engagement
- [ ] F-PDF-07: PDF MouseSelection - verify pdf-annotator.jsx text selection covers all cases
- [ ] F-PDF-08: PDF MouseMonitor - verify integrated mouse tracking covers all needs
- [ ] F-PDF-10: PDF Popup - positioned popup for highlight details
- [ ] F-PDF-11: PDF coordinates lib - verify normalized ratio approach covers all coordinate needs
- [ ] F-PDF-17: PDF permission types - verify permission.service.js covers all PDF permissions
- [ ] F-PDF-18: PDF types - verify JavaScript approach covers type safety needs
- [ ] F-PDF-20: PDF Spinner - verify Mantine Loader covers PDF loading needs
- [ ] F-PDF-22: PDF styled container - verify inline styles cover all container styling
- [ ] F-EMAIL-17: Email check utility - verify server-side validation covers all email checks
- [ ] M-AUTH-04: MWR cross-app token bridge - enable and implement (currently returns 503)
- [ ] M-REV-01: Review list tabs - add Active/Priority/History/Archive status filtering tabs
- [ ] M-REV-02: Review create dialog - add PDF upload + template selection to create flow
- [ ] M-PDF-04: Highlight colors - align palette to MWR grey/green/red/purple
- [ ] M-PDF-10: PDF editor mode - full editor capabilities matching MWR
- [ ] M-STATUS-01: Review open/close toggle - dedicated toggle UI component
- [ ] M-STATUS-02: Review private toggle - dedicated toggle UI component
- [ ] M-STATUS-03: Mark all highlights resolved - bulk resolve action
- [ ] M-SEARCH-01: Review search - dedicated search component
- [ ] M-ARCHIVE-01: Archive review - double confirmation dialog
- [ ] M-SECT-01: Review sections view - dedicated sections view UI
- [ ] M-HOME-02: Home page - MWR-specific review-focused layout
- [ ] M-COLLAB-01: Collaborator management - frontend dialog for managing collaborators
- [ ] M-COLLAB-03: Collaborator expiry - frontend UI for setting expiry dates
- [ ] M-CHECK-01: Checklist templates - frontend management UI
- [ ] M-CHECK-05: Weekly checklist emails - verify parity with MWR weekly reports
- [ ] M-CHECK-08: Checklist dialog - verify add-checklist.jsx covers all MWR fields
- [ ] M-CHECK-09: Checklist details - dedicated details page
- [ ] M-CHECK-10: Checklists home - dedicated listing page
- [ ] M-CHECK-11: Checklists management - dedicated management page
- [ ] M-FILE-04: Fetch cached PDF - explicit cached PDF retrieval logic
- [ ] M-SET-01: Settings home - MWR-specific settings landing page
- [ ] M-SET-02: Settings users - MWR-specific user management UI
- [ ] M-SET-03: Settings teams - MWR-specific team management UI
- [ ] M-SET-05: Settings templates - MWR-specific template management UI
- [ ] M-SET-06: Settings checklists - dedicated settings page
- [ ] M-SET-07: Settings integrations - settings UI for integrations
- [ ] M-SET-10: Review template manage - dedicated management UI
- [ ] M-TENDER-01: Tender details dialog - frontend dialog component
- [ ] M-TENDER-02: Tender details holder - frontend component
- [ ] M-TENDER-04: Tender type/status/priority - frontend UI for field management
- [ ] M-UI-01: Collapsible sidebar - desktop resizable sidebar
- [ ] M-UI-04: Empty container - dedicated empty state component
- [ ] M-UI-05: Status label - verify Mantine Badge covers all MWR status types
- [ ] M-UI-08: User avatar - dedicated component with online status indicator
- [ ] M-UI-09: Loader/Spinner - verify functional parity
- [ ] M-UI-10: Header text - verify Mantine Title/Text covers all MWR header needs
- [ ] M-UI-11: Styled text field - verify Mantine TextInput covers all MWR field styles
- [ ] M-HOOK-01: useGetUserType - verify server-side user.role covers all MWR type checks
- [ ] M-HOOK-06: useLogger - verify server-side logger covers all MWR logging needs
- [ ] M-GUARD-02: ProtectedPartnerRoute - verify permission-based access blocks non-partners
- [ ] M-MISC-02: Conversions - verify utils.js + date-utils.js cover MWR conversions
- [ ] M-MISC-03: Firebase functions - verify all MWR Firebase calls have equivalents
- [ ] M-MISC-08: Splash screen - branded splash screen for MWR domain
- [ ] M-MISC-09: Permission types - verify permission.service.js covers all MWR permission types
- [ ] M-MISC-10: Sections view - dedicated sections view UI
- [ ] M-MISC-13: Types definition - verify JavaScript approach covers MWR type safety
- [ ] M-SW-02: Service worker update banner - update notification UI for MWR domain
- [ ] M-FUNC-02: User utils - verify server-side equivalent covers all MWR user utilities
